config/routes.rb
Rails.application.routes.draw do
 
  resource :registration
  resource :session
  resource :password_reset
  resource :password
  root "main#index"
  resources :products
  delete '/products/:id', to: 'products#destroy', as: 'delete_product'
  resource :cart, only: [:show]
  post 'add_to_cart/:product_id', to: 'carts#add_to_cart', as: 'cart_add_to_cart'
  delete '/remove_from_cart/:id', to: 'carts#remove_from_cart', as: 'remove_from_cart'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_one :cart, dependent: :destroy

    validates :email, presence: true
    normalizes :email, with: ->(email) {email.strip.downcase}

    ROLES = %w{admin}

    def admin?
        role == "admin"
    end

    generates_token_for :password_reset, expires_in: 15.minutes do
        password_salt&.last(10)
    end

    generates_token_for :email_confirmation, expires_in: 24.hours do
        email
    end
end

app/controllers/Products_controller.rb
class ProductsController < ApplicationController
    before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]
  
    def index
      @products = Product.all
      @cart = current_user.cart
    end
    
    def show
      @product = Product.find(params[:id])
    end

    def new
      @product = Product.new
    end
  
    def create
      @product = Product.new(product_params)
  
      if @product.save
        redirect_to @product, notice: 'Product was successfully created.'
      else
        render :new
      end
    end
  
    def edit
      @product = Product.find(params[:id])
    end
  
    def update
      @product = Product.find(params[:id])
  
      if @product.update(product_params)
        redirect_to @product, notice: 'Product was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @product = Product.find(params[:id])
      @product.destroy
  
      redirect_to products_path, notice: 'Product was successfully destroyed.'
    end
  
    private
  
    def require_admin
      redirect_to root_path, alert: 'You do not have permission' unless current_user&.admin?
    end

    def product_params
      params.require(:product).permit(:name, :description, :price)
    end

end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private

    def authenticate_user!
      redirect_to root_path, alert: "You must be logged in to do that." unless user_signed_in?
    end

    def current_user
        Current.user ||= authenticate_user_from_session
    end
    helper_method :current_user

    def authenticate_user_from_session
      user_id = session[:user_id]
      User.find_by(id: user_id) if user_id.present? && User.exists?(user_id)
    end

    def user_signed_in?
      current_user.present?
    end
    helper_method :user_signed_in?

    def login(user)
        Current.user = user
        reset_session
        if user.present?
          session[:user_id] = user.id
        else
          Rails.logger.error("User is nil in login method")
        end
    end

    def logout(user)
      Current.user = nil
      reset_session
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :require_login
  
    def show
      @cart = current_user&.cart || Cart.new
    end
  
    def add_to_cart
      product = Product.find(params[:product_id])
      current_user.create_cart unless current_user.cart
      current_user.cart.cart_items.create(product: product, quantity: 1)
      redirect_to products_path, notice: 'Product added to cart successfully!'
    end
  
    def remove_from_cart
      cart_item = CartItem.find(params[:id])
      cart_item.destroy
      redirect_to cart_path, notice: 'Product removed from cart successfully!'
    end
  
    private
  
    def require_login
      redirect_to login_path, alert: 'Please log in to access your cart' unless current_user
    end
end
  

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
      
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
before_action :set_user_by_token, only: [:edit, :update]

    def new
      
    end

    def create
      if (user = User.find_by(email: params[:email]))
        PasswordMailer.with(
            user: user,
            token: user.generate_token_for(:password_reset)
        ).password_reset.deliver_later
      end

      redirect_to root_path, notice: "Check your email to reset your password."
    end

    def edit
      
    end

    def update
      if @user.update(password_params)
        redirect_to new_session_path, notice: "Your password has been reset successfully.Please login."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def set_user_by_token
        @user = User.find_by_token_for(:password_reset, params[:token])
        redirect_to new_password_reset_path alert: "Invalid token, please try again." unless @user.present?
    end

    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :authenticate_user!

    def edit
      
    end

    def update
      if current_user.update(password_params)
        redirect_to edit_password_path, notice: "Your password has been updated successfully."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def password_params
        params.require(:user).permit(
            :password,
            :password_confirmation,
            :password_challenge
        ).with_defaults(password_challenge: "")
      
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(registration_params)
        if @user.save
            login @user
            redirect_to products_path
        else
            render :new, status: :unprocessable_entity
        end
    end
    
    private

    def registration_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
      
    end

    def create
      if user = User.authenticate_by(email: params[:email], password: params[:password])
        login user
        redirect_to products_url, notice: "You have signed successfully."
      else
        flash[:alert] = "Invalid email or password."
        render :new, status: :unprocessable_entity
      end
    end
    
    def destroy
        logout current_user
        redirect_to root_path, notice: "You have been logged out."
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/show.html.erb
<div class="shopping-cart">
  <h2 style="text-align:center;">Your Shopping Cart</h2>

  <% if @cart && @cart.cart_items.any? %>
    <ul class="cart-items">
      <% @cart.cart_items.each do |cart_item| %>
        <li class="cart-item">
          <span class="product-name"><%= cart_item.product.name %></span> -
          <span class="quantity">Quantity: <%= cart_item.quantity %></span>
          <%= link_to 'Remove from Cart', remove_from_cart_path(cart_item), method: :delete, data: {
        turbo_method: :delete,
        turbo_confirm: "Product will be removed from the cart?"
      }, class: 'remove-link' %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p class="empty-cart">Your cart is empty.</p>
  <% end %>

  <%= link_to "Back to products", products_url, class: 'back-link' %>
</div>
<style>
  .shopping-cart {
  margin: 20px;
}

.cart-items {
  list-style-type: none;
  padding: 0;
}

.cart-item {
  margin-bottom: 10px;
}

.product-name {
  font-weight: bold;
}

.quantity {
  margin-left: 10px;
}

.remove-link {
  color: red;
  text-decoration: none;
  margin-left: 10px;
}

.remove-link:hover {
  text-decoration: underline;
}

.empty-cart {
  color: #777;
}

.back-link {
  display: block;
  margin-top: 20px;
  color: #007bff;
  text-decoration: none;
}

.back-link:hover {
  text-decoration: underline;
}

</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div><%= notice %></div>
    <div><%= alert %></div>
   <nav class="navbar">
      <div class="navbar-container">
        <% if user_signed_in? %>
          <%= link_to 'Home', root_path, class: "navbar-link" %>
          <%= link_to "Edit Password", edit_password_path, class: "navbar-link" %>
          <%= button_to "Log out", session_path, method: :delete, class: "navbar-button" %>
        <% else %>
          <%= link_to 'Home', root_path, class: "navbar-link" %>
          <%= link_to "Sign Up", new_registration_path, class: "navbar-link" %>
          <%= link_to "Log In", new_session_path, class: "navbar-link" %>
        <% end %>
      </div>
  </nav>
  <style>
    .navbar {
  background-color: #333;
  padding: 10px 0;
}

.navbar-container {
  max-width: 960px;
  margin: 0 auto;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.navbar-link {
  color: #FFD700;
  text-decoration: none;
  padding: 5px 10px;
}

.navbar-link:hover {
  background-color: #555;
}

.navbar-button {
  background-color: #d9534f;
  color: #FFD700;
  border: none;
  padding: 5px 10px;
  border-radius: 3px;
  cursor: pointer;
}

.navbar-button:hover {
  background-color: #c9302c;
}

  </style>
    
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1 style="text-align:center;">Welcome to Shopping App</h1>
<style>
        .centered {
            display: flex;
            justify-content: center;
        }
    </style>
<div class="centered">
        <img src="https://cdn.pixabay.com/photo/2017/12/15/19/07/ecommerce-3021581_1280.jpg" alt="Shopping image" width="600" height="500">
</div>

app/views/password_resets/edit.html.erb
<br>
<br>
<div class="form-container">
    <h1>Reset Your Password</h1>

    <%= form_with model: @user, url: password_reset_path(token: params[:token]) do |form|%>
        <%if form.object.errors.any?%>
            <% form.object.errors.full_messages.each do |message|%>
                <div><%= message %></div>
            <% end %>
        <% end %>


        <div>
            <%= form.label :password %>
            <%= form.password_field :password %>
        </div>

        <div>
            <%= form.label :password_confirmation %>
            <%= form.password_field :password_confirmation %>
        </div>

        <div>
            <%= form.submit "Reset Password" %>
        </div>

    <% end %>
</div>
<style>
     .form-container {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }
</style>

app/views/password_resets/new.html.erb
<div class="form-cotainer">
    <h1>Reset Your Password</h1>
    <%= form_with model: @user, url: password_reset_path do |form|%>
   
    <div>
        <%= form.label :email %>
        <%= form.email_field :email %>
    </div>


    <div>
        <%= form.submit "Reset Password" %>
    </div>

<% end %>
</div>
<style>
     .form-container {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }
</style>

app/views/products/edit.html.erb
<br>
<br>
<div class="form-container">
  <h2 style="text-align:center;">Edit Product</h2>

  <%= form_for @product do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <%= f.label :price %>
    <%= f.text_field :price %>

    <%= f.submit 'Update Product' %>
  <% end %>

  <%= link_to "Back to products", products_url%>
</div>
<style>
    .form-container {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }
</style>

app/views/products/index.html.erb
<h1 style="text-align:center">All Products</h1>
<div class="product-list">
  <% @products.each do |product| %>
    <div class="product">
      <h3><%= product.name %></h3>
      <p><%= product.description %></p>
      <p><strong>Price: <%= number_to_currency(product.price) %></strong></p>
      
      <% if current_user&.admin? %>
        <div class="admin-actions">
          <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-secondary' %>
          <%= link_to 'Delete', delete_product_path(product), method: :delete, data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          }, class: 'btn btn-danger' %>
        </div>
      <% else %>
        <%= button_to 'Add to Cart', cart_add_to_cart_path(@cart, product_id: product.id), method: :post, class: 'btn btn-primary' %>
      <% end %>
    </div>
  <% end %>
</div>
<br>
<br>
<div>
  <% if current_user&.admin? %>
    <%= link_to 'Add Product', new_product_path, class: 'btn btn-success' %>
  <% else %>
    <%= link_to 'Show Shopping Cart', cart_path, class: 'btn btn-primary' %>
  <% end %>
</div>
<style>
  .product-list {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 20px;
}

.product {
  background-color: #f9f9f9;
  padding: 20px;
  border-radius: 5px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.admin-actions {
  margin-top: 10px;
}

.btn {
  display: inline-block;
  padding: 10px 20px;
  text-decoration: none;
  color: #fff;
  border-radius: 5px;
  cursor: pointer;
  transition: background-color 0.3s ease;
}

.btn-primary {
  background-color: #007bff;
}

.btn-primary:hover {
  background-color: #0056b3;
}

.btn-secondary {
  background-color: #6c757d;
}

.btn-secondary:hover {
  background-color: #495057;
}

.btn-danger {
  background-color: #dc3545;
}

.btn-danger:hover {
  background-color: #c82333;
}

.btn-success {
  background-color: #28a745;
}

.btn-success:hover {
  background-color: #218838;
}

</style>

app/views/products/new.html.erb
<div class="new-product-form">
  <h2 style="text-align:center;">New Product</h2>

  <%= form_for Product.new, html: { class: 'product-form' } do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :price %>
      <%= f.text_field :price, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit 'Create Product', class: 'btn btn-primary' %>
    </div>
  <% end %>

  <%= link_to "Back to products", products_url, class: 'btn btn-secondary' %>
</div>

<style>
  .product-form {
  background-color: #f9f9f9;
  padding: 20px;
  border-radius: 5px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.form-group {
  margin-bottom: 20px;
}

.form-control {
  width: 100%;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 5px;
  font-size: 16px;
}

.btn {
  display: inline-block;
  padding: 10px 20px;
  text-decoration: none;
  color: #fff;
  border-radius: 5px;
  cursor: pointer;
  transition: background-color 0.3s ease;
}

.btn-primary {
  background-color: #007bff;
}

.btn-primary:hover {
  background-color: #0056b3;
}

.btn-secondary {
  background-color: #6c757d;
}

.btn-secondary:hover {
  background-color: #495057;
}

</style>

app/views/products/show.html.erb
<div class="about-product">
  <h1 style="text-align:center;">About <%= @product.name %></h1>

  <div class="product-details">
    <h2><%= @product.name %></h2>
    <p><strong>Description:</strong> <%= @product.description %></p>
    <p><strong>Price:</strong> <%= number_to_currency(@product.price) %></p>
  </div>

  <% if current_user&.admin? %>
    <div class="admin-actions">
      <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-primary' %>
      <%= link_to 'Delete', delete_product_path(@product), method: :delete, data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      }, class: 'btn btn-danger' %>
    </div>
  <% end %>

  
  <%= link_to "Back to products", products_url, class: 'btn btn-secondary' %>
</div>
<style>
  .about-product {
  margin: 20px;
}

.product-details {
  background-color: #f9f9f9;
  padding: 20px;
  border-radius: 5px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  margin-bottom: 20px;
}

.admin-actions {
  margin-bottom: 20px;
}

.btn {
  display: inline-block;
  padding: 10px 20px;
  text-decoration: none;
  color: #fff;
  border-radius: 5px;
  cursor: pointer;
  transition: background-color 0.3s ease;
}

.btn-primary {
  background-color: #007bff;
}

.btn-primary:hover {
  background-color: #0056b3;
}

.btn-danger {
  background-color: #dc3545;
}

.btn-danger:hover {
  background-color: #c82333;
}

.btn-success {
  background-color: #28a745;
}

.btn-success:hover {
  background-color: #218838;
}

.btn-secondary {
  background-color: #6c757d;
}

.btn-secondary:hover {
  background-color: #495057;
}

</style>